// ACTION CONSTANTS

export const ADD_LOGIN_USER = "ADD_LOGIN_USER"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const SHOW_COMPONENT_HIDE_OTHER = "SHOW_COMPONENT_HIDE_OTHER"
export const SHOW_COMPONENT = "SHOW_COMPONENT"
export const HIDE_COMPONENT = "HIDE_COMPONENT"
export const ADD_SSR_FLAG = "ADD_SSR_FLAG"
export const CLEAR_SSR_FLAG = "CLEAR_SSR_FLAG"
export const SHOW_LOADER = "SHOW_LOADER"
export const HIDE_LOADER = "HIDE_LOADER"
export const ADD_PERMISSIONS = "ADD_PERMISSIONS"
export const ADD_PERMISSION = "ADD_PERMISSION"
export const EDIT_PERMISSION = "EDIT_PERMISSION"
export const DELETE_PERMISSION = "DELETE_PERMISSION"
export const ADD_ROLES = "ADD_ROLES"
export const ADD_ROLE = "ADD_ROLE"
export const EDIT_ROLE = "EDIT_ROLE"
export const DELETE_ROLE = "DELETE_ROLE"
export const ADD_USERS = "ADD_USERS"
export const ADD_USERS_WITH_ROLE_CATEGORY = "ADD_USERS_WITH_ROLE_CATEGORY"
export const ADD_USER = "ADD_USER"
export const EDIT_USER = "EDIT_USER"
export const DELETE_USER = "DELETE_USER"
export const ADD_ADMIN_USER = "ADD_ADMIN_USER"
export const UPDATE_ADMIN_USER = "UPDATE_ADMIN_USER"
export const DELETE_ADMIN_USER = "DELETE_ADMIN_USER"
export const ADMIN_EDITING_ROLE = "ADMIN_EDITING_ROLE"
export const ADD_CLIENTS = "ADD_CLIENTS"
export const ADD_CLIENT = "ADD_CLIENT"
export const UPDATE_CLIENT = "UPDATE_CLIENT"
export const DELETE_CLIENT = "DELETE_CLIENT"

// estimation constants
export const ADD_ESTIMATIONS = "ADD_ESTIMATIONS"
export const ADD_ESTIMATION = "ADD_ESTIMATION"
export const EDIT_ESTIMATION = "EDIT_ESTIMATION"
export const DELETE_ESTIMATION = "DELETE_ESTIMATION"
export const ESTIMATION_TASK_DELETE = "ESTIMATION_TASK_DELETE"
export const ESTIMATION_TASK_EDIT_REQUESTED = "ESTIMATION_TASK_EDIT_REQUESTED"
export const ESTIMATION_TASK_EDIT_GRANTED = "ESTIMATION_TASK_EDIT_GRANTED"
export const REQUEST_FOR_TASK_EDIT_PERMISSION = "REQUEST_FOR_TASK_EDIT_PERMISSION"
export const DELETE_ESTIMATION_TASK = "DELETE_ESTIMATION_TASK"
export const DELETE_ESTIMATION_FEATURE = "DELETE_ESTIMATION_FEATURE"
export const UPDATE_USER_PROFILE_STATE = "UPDATE_USER_PROFILE_STATE"
export const EXPAND_FEATURE = "EXPAND_FEATURE"
export const EXPAND_TASK = "EXPAND_TASK"
export const EXPAND_TASK_AND_FEATURE = "EXPAND_TASK_AND_FEATURE"
export const ADD_FILTERED_ESTIMATIONS = "ADD_FILTERED_ESTIMATIONS"
export const CLEAR_FILTER_FROM_ESTIMATION = "CLEAR_FILTER_FROM_ESTIMATION"

//project constants
export const ADD_PROJECTS = "ADD_PROJECTS"
export const ADD_PROJECT = "ADD_PROJECT"
export const EDIT_PROJECT = "EDIT_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"

export const SELECT_ESTIMATION = "SELECT_ESTIMATION"
export const ADD_ESTIMATION_TASK = "ADD_ESTIMATION_TASK"
export const UPDATE_ESTIMATION_TASK = "UPDATE_ESTIMATION_TASK"
export const ADD_ESTIMATION_FEATURE = "ADD_ESTIMATION_FEATURE"
export const UPDATE_ESTIMATION_FEATURE = "UPDATE_ESTIMATION_FEATURE"
export const MOVE_TASK_IN_FEATURE = "MOVE_TASK_IN_FEATURE"
export const MOVE_TASK_OUTOF_FEATURE = "MOVE_TASK_OUTOF_FEATURE"
export const UPDATE_SELECTED_ESTIMATION = "UPDATE_SELECTED_ESTIMATION"

//technology constants
export const ADD_TECHNOLOGIES = "ADD_TECHNOLOGIES"
export const ADD_TECHNOLOGY = "ADD_TECHNOLOGY"
export const DELETE_TECHNOLOGY = "DELETE_TECHNOLOGY"

//Leave request Constants
export const ADD_LEAVE_REQUEST = "ADD_LEAVE_REQUEST"
export const ADD_LEAVE_REQUESTS = "ADD_LEAVE_REQUESTS"
export const CANCEL_LEAVE_REQUEST = "CANCEL_LEAVE_REQUEST"
export const ADD_LEAVE_TYPES = "ADD_LEAVE_TYPES"
export const SELECTED_LEAVE_DETAIL = "SELECTED_LEAVE_DETAIL"

//Release  Constants
export const ADD_RELEASES = "ADD_RELEASES"
export const ADD_RELEASE_PROJECT_SELECTED = "ADD_RELEASE_PROJECT_SELECTED"
export const ADD_RELEASES_TASK = "ADD_RELEASES_TASK"
export const RELEASE_TASK_PLAN_SELECTED = "RELEASE_TASK_PLAN_SELECTED"
export const ADD_RELEASES_TASK_PLANNING = "ADD_RELEASES_TASK_PLANNING"
export const ADD_TASK_PLANNING_TO_STATE = "ADD_TASK_PLANNING_TO_STATE"
export const DELETE_TASK_PLAN_FROM_STATE = "DELETE_TASK_PLAN_FROM_STATE"
export const ADD_DEVELOPER_FILTERED = "ADD_DEVELOPER_FILTERED"

//repository constants
export const SELECT_REPOSITORY = "SELECT_REPOSITORY"
export const SELECT_TASK_FROM_REPOSITORY = "SELECT_TASK_FROM_REPOSITORY"
export const SELECT_FEATURE_FROM_REPOSITORY = "SELECT_FEATURE_FROM_REPOSITORY"

//attendence Settings

export const ADD_UPDATE_ATTENDENCE_SETTING = "ADD_UPDATE_ATTENDENCE_SETTING"

