export const ALREADY_EXISTS = "ALREADY_EXISTS"
export const NOT_FOUND = "NOT_FOUND"
export const EMAIL_ALREADY_USED = "EMAIL_ALREADY_USED"
export const ACCESS_DENIED = "ACCESS_DENIED"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const IDENTIFIER_MISSING = "IDENTIFIER_MISSING"
export const UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
export const PASSWORD_NOT_MATCHED = "PASSWORD_NOT_MATCHED"


// HTML CODES

export const HTTP_OK = 200
export const HTTP_CREATED = 201
export const HTTP_ACCEPTED = 202
export const HTTP_NO_CONTENT = 204

export const HTTP_BAD_REQUEST = 400
export const HTTP_UNAUTHORIZED = 401
export const HTTP_FORBIDDEN = 403
export const HTTP_NOT_FOUND = 404

export const HTTP_SERVER_ERROR = 500

