export const ALREADY_EXISTS = 'ALREADY_EXISTS'
export const NOT_EXISTS = 'NOT_EXISTS'
export const NOT_FOUND = 'NOT_FOUND'
export const EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED'
export const ACCESS_DENIED = 'ACCESS_DENIED'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const IDENTIFIER_MISSING = 'IDENTIFIER_MISSING'
export const UNEXPECTED_ERROR = 'UNEXPECTED_ERROR'
export const PASSWORD_NOT_MATCHED = 'PASSWORD_NOT_MATCHED'
export const API_VALIDATION_FAILED = 'API_VALIDATION_FAILED'
export const BAD_ARGUMENTS = 'BAD_ARGUMENTS'
export const INVALID_USER = 'INVALID_USER'
export const INVALID_OPERATION = 'INVALID_OPERATION'
export const UNIMPLEMENTED_SO_FAR = 'UNIMPLEMENTED_SO_FAR'

//task and feature approval error codes
export const TASK_APPROVAL_ERROR = 'TASK_APPROVAL_ERROR'
export const FEATURE_APPROVAL_ERROR = 'FEATURE_APPROVAL_ERROR'
export const FEATURE_DETAIL_ERROR = 'FEATURE_DETAIL_ERROR'
export const TASK_APPROVAL_FEATURE_ERROR = 'TASK_APPROVAL_FEATURE_ERROR'
export const MOVE_TASK_IN_FEATURE_ERROR = 'MOVE_TASK_IN_FEATURE_ERROR'
export const TASK_FROM_REPOSITORY_ERROR = 'TASK_FROM_REPOSITORY_ERROR'
export const FEATURE_FROM_REPOSITORY_ERROR = 'FEATURE_FROM_REPOSITORY_ERROR'
export const STILL_PENDING_TASKS_AND_FEATURE_ERROR = 'STILL_PENDING_TASKS_AND_FEATURE_ERROR'
export const STILL_PENDING_TASKS_ERROR = 'STILL_PENDING_TASKS_ERROR'
export const NO_TASKS_ERROR = 'NO_TASKS_ERROR'
export const NO_ESTIMATED_HOUR_ERROR = 'NO_ESTIMATED_HOUR_ERROR'
export const TIME_OVER_FOR_REREPORTING = 'TIME_OVER_FOR_REREPORTING'
export const REPORT_STATUS_NOT_ALLOWED = 'REPORT_STATUS_NOT_ALLOWED'
export const TIME_OVER = 'TIME_OVER'
export const ALREADY_REPORTED = 'ALREADY_REPORTED'
export const NOT_ALLOWED_TO_ADD_EXTRA_EMPLOYEE = 'NOT_ALLOWED_TO_ADD_EXTRA_EMPLOYEE'
export const DATA_INCONSISTENT = 'DATA_INCONSISTENT'
export const CANT_PLAN = 'CANT_PLAN'
export const BEYOND_TODAY = 'BEYOND_TODAY'


// HTML CODES
export const HTTP_OK = 200
export const HTTP_CREATED = 201
export const HTTP_ACCEPTED = 202
export const HTTP_NO_CONTENT = 204

export const HTTP_BAD_REQUEST = 400
export const HTTP_UNAUTHORIZED = 401
export const HTTP_FORBIDDEN = 403
export const HTTP_NOT_FOUND = 404

export const HTTP_SERVER_ERROR = 500

