export const EMAIL_BODY_LEAVE_RAISED = "email_body_leave_raised"
export const EMAIL_SUBJECT_LEAVE_RAISED = "email_subject_leave_raised"
export const NOTIFICATION_LEAVE_RAISED = "notification_leave_raised"
export const EMAIL_BODY_TASK_ASSIGNED = "email_body_task_assigned"
export const EMAIL_SUBJECT_TASK_ASSIGNED = "email_subject_task_assigned"
export const NOTIFICATION_TASK_ASSIGNED = "notification_task_assigned"