import * as EC from "../errorcodes";
import * as SC from "../serverconstants";
import * as MDL from "../models";
import mongoose from 'mongoose'
import AppError from '../AppError'
import * as V from "../validation"
import * as U from "../utils"
import _ from "lodash"

mongoose.Promise = global.Promise


let leaveSchema = mongoose.Schema({
    user: {
        _id: mongoose.Schema.ObjectId,
        firstName: {type: String, required: true},
        lastName: {type: String, required: true},
    },
    status: {
        type: String,
        enum: SC.ALL_LEAVE_STATUS_ARRAY
    },
    dayType: {type: String, enum: SC.LEAVE_TYPE_DAY_ARRAY},
    approver: {
        _id: mongoose.Schema.ObjectId,
        name: {type: String, required: false},
        reason: {type: String, required: false}
    },
    leaveType: {
        _id: mongoose.Schema.ObjectId,
        name: {type: String, required: false}
    },
    description: {type: String, required: false},
    startDate: {type: Date, required: true},
    startDateString: {type: String, required: true},
    endDate: {type: Date, required: true},
    endDateString: {type: String, required: true},
    numberOfLeaveDays: {type: Number, required: true},
    created: {type: Date, default: Date.now()},
    updated: {type: Date, default: Date.now()}
})


leaveSchema.statics.getAllLeaves = async (status, user) => {
    let leaves
    if (U.userHasRole(user, SC.ROLE_HIGHEST_MANAGEMENT_ROLE)) {
        leaves = await getLeaves(status, user)
    } else {
        leaves = await getUserLeaves(status, user)
    }

    leaves = leaves && leaves.length ? leaves.map(leave => Object.assign({}, leave.toObject(), {
            canDelete: leave.user._id.toString() === user._id.toString(),
            canCancel: _.includes([SC.LEAVE_STATUS_RAISED, SC.LEAVE_STATUS_PENDING], leave.status) && U.userHasRole(user, SC.ROLE_HIGHEST_MANAGEMENT_ROLE),
            canApprove: _.includes([SC.LEAVE_STATUS_RAISED, SC.LEAVE_STATUS_PENDING], leave.status) && U.userHasRole(user, SC.ROLE_HIGHEST_MANAGEMENT_ROLE)
        })
    ) : []
    return leaves
}


const getUserLeaves = async (status, user) => {

    if (status && status.toLowerCase() === 'all') {
        return await LeaveModel.find({
            "user._id": mongoose.Types.ObjectId(user._id)
        }).exec()
    } else {
        return await LeaveModel.find({
            "user._id": mongoose.Types.ObjectId(user._id),
            "status": status
        }).exec()
    }
}

const getLeaves = async (status, user) => {
    if (status && status.toLowerCase() === 'all') {
        return await LeaveModel.find({}).exec()
    } else {
        return await LeaveModel.find({
            "status": status
        }).exec()
    }
}

leaveSchema.statics.raiseLeaveRequest = async (leaveInput, user, schemaRequested) => {
    if (schemaRequested)
        return V.generateSchema(V.leaveRequestAdditionStruct)

    V.validate(leaveInput, V.leaveRequestAdditionStruct)


    let startDateMoment = U.momentInUTC(leaveInput.startDate)
    let endDateMoment = U.momentInUTC(leaveInput.endDate)

    if (!endDateMoment.isSameOrAfter(startDateMoment))
        throw new AppError("End date is not valid", EC.INVALID_OPERATION, EC.HTTP_BAD_REQUEST)

    if (!startDateMoment.isSameOrAfter(U.getTodayStartingMoment()))
        throw new AppError("Leave start date should be greater than or equal to today date", EC.INVALID_OPERATION, EC.HTTP_BAD_REQUEST)


    if (!startDateMoment.isValid() || !endDateMoment.isValid())
        throw new AppError("Invalid Start date or End Date generated by moment", EC.INVALID_OPERATION, EC.HTTP_BAD_REQUEST)

    let leaveDaysCount = endDateMoment.diff(startDateMoment, 'days')
    if (!leaveDaysCount)
        leaveDaysCount = 0

    leaveDaysCount = Number(leaveDaysCount)

    await MDL.WarningModel.addEmployeeAskForLeave(startDateMoment, endDateMoment, user)
    let leaveType = await MDL.LeaveTypeModel.findById(mongoose.Types.ObjectId(leaveInput.leaveType._id))
    let newLeave = new LeaveModel()

    newLeave.startDate = startDateMoment
    newLeave.startDateString = leaveInput.startDate
    newLeave.endDate = endDateMoment
    newLeave.endDateString = leaveInput.endDate

    //note:- this case for current date raise leave
    newLeave.numberOfLeaveDays = leaveDaysCount + 1
    newLeave.leaveType = leaveType
    newLeave.status = SC.LEAVE_STATUS_RAISED
    newLeave.user = user
    newLeave.dayType = leaveInput.dayType ? leaveInput.dayType : SC.LEAVE_TYPE_FULL_DAY

    await newLeave.save(leaveInput)
    newLeave = newLeave.toObject()
    newLeave.canDelete = true
    newLeave.canCancel = U.userHasRole(user, SC.ROLE_HIGHEST_MANAGEMENT_ROLE) ? true : false
    newLeave.canApprove = U.userHasRole(user, SC.ROLE_HIGHEST_MANAGEMENT_ROLE) ? true : false
    return newLeave
}

leaveSchema.statics.cancelLeaveRequest = async (leaveID, user) => {
    let Roles = await MDL.UserModel.findById()
    let leaveRequest = await LeaveModel.findById(mongoose.Types.ObjectId(leaveID))

    if (!leaveRequest) {
        throw new AppError("leave request Not Found", EC.NOT_FOUND, EC.HTTP_BAD_REQUEST)
    }

    leaveRequest.status = SC.LEAVE_STATUS_CANCELLED
    await leaveRequest.save()

    leaveRequest = leaveRequest.toObject()
    leaveRequest.canDelete = user._id.toString() === leaveRequest.user._id.toString()
    leaveRequest.canCancel = true
    leaveRequest.canApprove = true
    return leaveRequest
}

leaveSchema.statics.approveLeaveRequest = async (leaveID, user) => {
    let leaveRequest = await LeaveModel.findById(mongoose.Types.ObjectId(leaveID),)

    if (!leaveRequest) {
        throw new AppError("leave request Not Found", EC.NOT_FOUND, EC.HTTP_BAD_REQUEST)
    }

    leaveRequest.status = SC.LEAVE_STATUS_APPROVED
    await leaveRequest.save()

    leaveRequest = leaveRequest.toObject()
    leaveRequest.canDelete = user._id.toString() === leaveRequest.user._id.toString()
    leaveRequest.canCancel = true
    leaveRequest.canApprove = true
    return leaveRequest
}

leaveSchema.statics.deleteLeave = async (leaveID, user) => {

    let leaveRequest = await LeaveModel.findById(mongoose.Types.ObjectId(leaveID))

    if (!leaveRequest) {
        throw new AppError("leave request Not Found", EC.NOT_FOUND, EC.HTTP_BAD_REQUEST)
    }
    if (leaveRequest.user._id.toString() !== user._id.toString()) {
        throw new AppError("This leave is not belongs to your leave ,user can delete his own leave only", EC.ACCESS_DENIED, EC.HTTP_BAD_REQUEST)
    }

    return await leaveRequest.findByIdAndRemove(mongoose.Types.ObjectId(leaveID))
}

const LeaveModel = mongoose.model("Leave", leaveSchema)
export default LeaveModel