// tabs
export const PERMISSION_TAB = "Permission"
export const ROLE_TAB = "Role"
export const USER_TAB = "User"
export const ADMIN_USER_TAB = "Manage User"
export const USER_PROFILE_TAB = "Profile"
export const ADMIN_PERMISSION_TAB = "Manage Permission"

// forms
export const PERMISSION_FORM = "PERMISSION_FORM"
export const ROLE_FORM = "ROLE_FORM"
export const USER_FORM = "USER_FORM"
export const ADMIN_USER_FORM = "ADMIN_USER_FORM"
export const USER_PROFILE_FORM = "USER_PROFILE_FORM"
export const ADMIN_ROLE_FORM = "ADMIN_ROLE_FORM"
export const CLIENT_FORM = "CLIENT_FORM"
export const PROJECT_FORM = "PROJECT_FORM"
export const TECHNOLOGY_FORM = "TECHNOLOGY_FORM"
export const LEAVE_REQUEST_FORM = "LEAVE_REQUEST_FORM"
export const ATTENDANCE_SETTING_FORM = "ATTENDANCE_SETTING_FORM"


// lists
export const PERMISSION_LIST = "PERMISSION_LIST"
export const ROLE_LIST = "ROLE_LIST"
export const USER_LIST = "USER_LIST"
export const ADMIN_USER_LIST = "ADMIN_USER_LIST"
export const ADMIN_ROLE_LIST = "ADMIN_ROLE_LIST"
export const ESTIMATION_LIST = "ESTIMATION_LIST"
export const PROJECT_LIST = "PROJECT_LIST"
export const TECHNOLOGIES_LIST = "TECHNOLOGIES_LIST"
export const CLIENT_LIST = "CLIENT_LIST"
export const RAISE_LEAVE_LIST = "RAISE_LEAVE_LIST"
export const RELEASE_LIST = "RELEASE_LIST"
export const RELEASE_DETAIL_LIST = "RELEASE_DETAIL_LIST"
export const RELEASE_TASK_DETAIL_PAGE = "RELEASE_TASK_DETAIL_PAGE"


// dialogs
export const ESTIMATION_INITIATE_DIALOG = "ESTIMATION_INITIATE_DIALOG"
export const ESTIMATION_TASK_DIALOG = "ESTIMATION_TASK_DIALOG"
export const TECHNOLOGY_FORM_DIALOG = "TECHNOLOGY_FORM_DIALOG"
export const PROJECT_FORM_DIALOG = "PROJECT_FORM_DIALOG"
export const CLIENT_FORM_DIALOG = "CLIENT_FORM_DIALOG"
export const LEAVE_REQUEST_FORM_DIALOG = "LEAVE_REQUEST_FORM_DIALOG"
export const ESTIMATION_FEATURE_DIALOG = "ESTIMATION_FEATURE_DIALOG"
export const MOVE_TASK_TO_FEATURE_FORM_DIALOG = "MOVE_TASK_TO_FEATURE_FORM_DIALOG"
export const ESTIMATION_SUGGEST_TASK_FORM_DIALOG = "ESTIMATION_SUGGEST_TASK_FORM_DIALOG"
export const ESTIMATION_SUGGEST_FEATURE_FORM_DIALOG = "ESTIMATION_SUGGEST_FEATURE_FORM_DIALOG"
export const ESTIMATION_PROJECT_AWARD_FORM_DIALOG = "ESTIMATION_PROJECT_AWARD_FORM_DIALOG"
export const REPOSITORY_TASK_DETAIL_DIALOG = "REPOSITORY_TASK_DETAIL_DIALOG"
export const REPOSITORY_FEATURE_DETAIL_DIALOG = "REPOSITORY_FEATURE_DETAIL_DIALOG"
export const ESTIMATION_FILTER_DIALOG = "ESTIMATION_FILTER_DIALOG"
export const LEAVE_DETAIL_DIALOG = "LEAVE_DETAIL_DIALOG"
export const RELEASE_TASK_PLANNING_FORM_DIALOG = "RELEASE_TASK_PLANNING_FORM_DIALOG"
// pages
export const ESTIMATION_DETAIL_PAGE = "ESTIMATION_DETAIL_PAGE"


