// tabs
export const PERMISSION_TAB = "Permission"
export const ROLE_TAB = "Role"
export const USER_TAB = "User"
export const ADMIN_USER_TAB = "Manage User"
export const USER_PROFILE_TAB = "Profile"
export const ADMIN_PERMISSION_TAB = "Manage Permission"

// forms
export const PERMISSION_FORM = "PERMISSION_FORM"
export const ROLE_FORM = "ROLE_FORM"
export const USER_FORM = "USER_FORM"
export const ADMIN_USER_FORM = "ADMIN_USER_FORM"
export const USER_PROFILE_FORM = "USER_PROFILE_FORM"
export const ADMIN_ROLE_FORM = "ADMIN_ROLE_FORM"
export const CLIENT_FORM = "CLIENT_FORM"
export const PROJECT_FORM = "PROJECT_FORM"
export const TECHNOLOGY_FORM = "TECHNOLOGY_FORM"

// lists
export const PERMISSION_LIST = "PERMISSION_LIST"
export const ROLE_LIST = "ROLE_LIST"
export const USER_LIST = "USER_LIST"
export const ADMIN_USER_LIST = "ADMIN_USER_LIST"
export const ADMIN_ROLE_LIST = "ADMIN_ROLE_LIST"
export const ESTIMATION_LIST = "ESTIMATION_LIST"
export const PROJECT_LIST = "PROJECT_LIST"
export const TECHNOLOGIES_LIST = "TECHNOLOGIES_LIST"
export const CLIENT_LIST = "CLIENT_LIST"


// dialogs
export const ESTIMATION_INITIATE_DIALOG = "ESTIMATION_INITIATE_DIALOG"
export const ESTIMATION_TASK_DIALOG = "ESTIMATION_TASK_DIALOG"
export const TECHNOLOGY_FORM_DIALOG = "TECHNOLOGY_FORM_DIALOG"
export const PROJECT_FORM_DIALOG = "PROJECT_FORM_DIALOG"
export const CLIENT_FORM_DIALOG = "CLIENT_FORM_DIALOG"
export const ESTIMATION_FEATURE_DIALOG = "ESTIMATION_FEATURE_DIALOG"

// pages
export const ESTIMATION_DETAIL_PAGE = "ESTIMATION_DETAIL_PAGE"


